[project]
name = "ompl-rs"
version = "0.1.0"
description = "Add a short description here"
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
prepare-ompl = "test -e .ompl || git clone https://github.com/ompl/ompl.git .ompl"
prepare-ompl-cmake = "mkdir -p build/Release && cd build/Release && cmake ../../.ompl"
build-ompl = "cmake --build build/Release"
install-ompl = "cmake --install build/Release --prefix .pixi/envs/default"
setup-ompl = { depends_on = ["prepare-ompl", "prepare-ompl-cmake", "build-ompl", "install-ompl"] }

[dependencies]
cmake = ">=3.28.3,<3.29"
eigen = ">=3.4.0,<3.5"
boost = ">=1.84.0,<1.85"
pip = ">=24.0,<25"
python = "3.11.*"
pkgconfig = ">=1.5.5,<1.6"
gcc = ">=13.2.0,<13.3"
